plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - 01. Recap.md
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: minima